# Generated by Django 4.1.6 on 2023-02-12 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='')),
                ('berth_data', models.IntegerField(blank=True, null=True)),
                ('death_data', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
